# Join Statements - Lab

## Introduction

In this lab, you'll practice your knowledge of `JOIN` statements, using various types of joins and various methods for specifying the links between them.

## Objectives

You will be able to:

* Write SQL queries that make use of various types of joins
* Compare and contrast the various types of joins
* Discuss how primary and foreign keys are used in SQL
* Decide and perform whichever type of join is best for retrieving desired data

## CRM ERD

In this lab, you'll use the same customer relationship management (CRM) database that you saw from the previous lesson.
<img src='https://curriculum-content.s3.amazonaws.com/data-science/images/Database-Schema.png' width="600">

## Connecting to the Database
Import the necessary packages and connect to the database `'data.sqlite'`.

In [19]:
# Your code here
import sqlite3
import pandas as pd
conn = sqlite3.connect('data.sqlite')

## Select the names of all employees in Boston 

Hint: join the employees and offices tables. Select the first and last name.

In [20]:
# Your code here
query = """
SELECT firstName, lastName
FROM employees
JOIN offices
USING(officeCode)
WHERE city = 'Boston';

"""
pd.read_sql(query, conn)

  firstName   lastName
0     Julie   Firrelli
1     Steve  Patterson

## Are there any offices that have zero employees?
Hint: Combine the employees and offices tables and use a group by. Select the office code, city, and number of employees.

In [21]:
# Your code here
query = """
SELECT officeCode, city, employeeNumber, COUNT(employees.employeeNumber) AS employeeCount
FROM employees
JOIN offices
USING(officeCode)
GROUP BY officeCode
HAVING COUNT(officeCode) = 0;

"""
pd.read_sql(query, conn)

Empty DataFrame
Columns: [officeCode, city, employeeNumber, employeeCount]
Index: []

## Write 3 questions of your own and answer them

In [22]:
# Answers will vary
# Example question: 
"""
How many customers are there per office?
"""
query = """
SELECT offices.officeCode, offices.city,customerNumber,customerName, COUNT(customerNumber) AS customer_count
FROM customers
LEFT JOIN employees
    ON employees.employeeNumber = customers.salesRepEmployeeNumber
JOIN offices
    USING(officeCode)
GROUP BY officeCode;
"""

# Execute the query and load it into a pandas DataFrame
pd.read_sql(query, conn)

# Display the first 10 results
#f.head(10)

,officeCode,city,customerNumber,customerName,customer_count
0,1,San Francisco,112,Signal Gift Stores,12
1,2,Boston,157,Diecast Classics Inc.,12
2,3,NYC,131,Land of Toys Inc.,15
3,4,Paris,103,Atelier graphique,29
4,5,Tokyo,148,"Dragon Souveniers, Ltd.",5
5,6,Sydney,114,"Australian Collectors, Co.",10
6,7,London,121,Baane Mini Imports,17

In [23]:
"""
Question 1
Find the total amount of payments made by the customers for their orders

"""

# Your code here
query = ("""
SELECT C.contactLastName, C.contactFirstName, C.customerNumber,O.orderNumber, SUM(P.amount) AS total_payments
FROM customers AS C
LEFT JOIN payments as P 
USING(customerNumber)
JOIN orders as O
USING(customerNumber)
GROUP BY C.customerNumber
ORDER BY total_payments DESC
LIMIT 10;
""")

pd.read_sql(query, conn)

  contactLastName contactFirstName customerNumber orderNumber  total_payments
0          Freyre           Diego             141       10104     18609213.48
1          Nelson            Susan            124       10113      9931200.08
2        Ferguson            Peter            114       10120       902925.35
3       Natividad             Eric            148       10117       781255.15
4          Graham             Mike            323       10132       773110.40
5           Young             Jeff            151       10127       711655.80
6         Henriot            Paul             353       10121       634915.95
7          O'Hara             Anna            276       10148       548136.88
8        Petersen           Jytte             145       10105       537232.50
9           Brown            Julie            321       10159       529363.12

In [24]:
"""
Question 2
"""

# Your code here

'\nQuestion 2\n'

In [25]:
"""
Question 3
"""

# Your code here

'\nQuestion 3\n'

## Level Up 1: Display the names of every individual product that each employee has sold

Hint: You will need to use multiple `JOIN` clauses to connect all the way from employee names to product names.

In [31]:
# Your code here

query = """
SELECT employeeNumber, productName, lastName, firstName
FROM employees
LEFT JOIN customers
    ON employees.employeeNumber = customers.salesRepEmployeeNumber
JOIN orders
    USING(customerNumber)
JOIN orderdetails
    USING(orderNumber)
JOIN products
    USING(productCode)
GROUP BY productName,employeeNumber;
"""

# Execute the query and load it into a DataFrame
pd.read_sql(query, conn)

# Display the DataFrame
#df.head(10)

     employeeNumber                          productName   lastName firstName
0              1165  18th Century Vintage Horse Carriage   Jennings    Leslie
1              1166  18th Century Vintage Horse Carriage   Thompson    Leslie
2              1188  18th Century Vintage Horse Carriage   Firrelli     Julie
3              1216  18th Century Vintage Horse Carriage  Patterson     Steve
4              1286  18th Century Vintage Horse Carriage      Tseng  Foon Yue
...             ...                                  ...        ...       ...
1363           1501            The USS Constitution Ship       Bott     Larry
1364           1504            The USS Constitution Ship      Jones     Barry
1365           1612            The USS Constitution Ship      Marsh     Peter
1366           1621            The USS Constitution Ship      Nishi      Mami
1367           1702            The USS Constitution Ship     Gerard    Martin

[1368 rows x 4 columns]

## Level Up 2: Display the number of products each employee has sold

Alphabetize the results by employee last name.

Hint: Use the `quantityOrdered` column from `orderDetails`. Also, think about how to group the data when some employees might have the same first or last name.

In [ ]:
# Your code here
query = """
SELECT 
    employees.employeeNumber, 
    employees.lastName, 
    employees.firstName, 
    SUM(orderdetails.quantityOrdered) AS totalProductsSold
FROM employees
JOIN customers
    ON employees.employeeNumber = customers.salesRepEmployeeNumber
JOIN orders
    USING(customerNumber)
JOIN orderdetails 
    USING(orderNumber)
JOIN products
    USING(productCode)
GROUP BY employees.employeeNumber, employees.lastName, employees.firstName
ORDER BY employees.lastName, employees.firstName;
"""

# Execute the query and load the result into a pandas DataFrame
pd.read_sql(query, conn)

# Display the result
#df.head()

   employeeNumber   lastName firstName  totalProductsSold
0            1337     Bondur      Loui               6186
1            1501       Bott     Larry               8205
2            1401   Castillo    Pamela               9290
3            1188   Firrelli     Julie               4227
4            1611     Fixter      Andy               6246
5            1702     Gerard    Martin               4180
6            1370  Hernandez    Gerard              14231
7            1165   Jennings    Leslie              11854
8            1504      Jones     Barry               7486
9            1612      Marsh     Peter               6632
10           1621      Nishi      Mami               4923
11           1216  Patterson     Steve               5561
12           1166   Thompson    Leslie               4056
13           1286      Tseng  Foon Yue               5016
14           1323     Vanauf    George               7423

## Level Up 3: Display the names employees who have sold more than 200 different products

Hint: this is different from the previous question because the quantity sold doesn't matter, only the number of different products

In [ ]:
# Your code here
query = """
SELECT employeeNumber, lastName, firstName
    COUNT(products.productCode) AS ProductsSold
FROM employees
LEFT JOIN customers
    ON employees.employeeNumber = customers.salesRepEmployeeNumber
JOIN orders
    USING(customerNumber)
JOIN orderdetails 
    USING(orderNumber)
JOIN products
    USING(productCode)
GROUP BY employeeNumber
HAVING ProductsSold > 200;
"""

# Execute the query and load the result into a pandas DataFrame
pd.read_sql(query, conn)

# Display the result
#df.head()

DatabaseError: Execution failed on sql '
SELECT employeeNumber, lastName, firstName
    COUNT(products.productCode) AS ProductsSold
FROM employees
LEFT JOIN customers
    ON employees.employeeNumber = customers.salesRepEmployeeNumber
JOIN orders
    USING(customerNumber)
JOIN orderdetails
    USING(orderNumber)
JOIN products
    USING(productCode)
GROUP BY employeeNumber
HAVING ProductsSold > 200;
': near "(": syntax error

## Summary

Congrats! You practiced using join statements and leveraged your foreign keys knowledge!